rapidsai-community/rapidsai-csp-utils

colab/rapids-colab.sh
added version installation options through CLI
refactored code so you can quickly change install and verbiage parameters
=> Add options to install parameters, refactor code, update verbiage

colab/rapids-colab.sh
Updated script due to numba /six compatibility issues
=> Patch numba update incompatibility

colab/rapids-colab.sh
=> fix missing quote in rapids-colab.sh

colab/update_modules.py
adding try and except pyarrow doesn't install in some versions
Closes https://github.com/rapidsai/rapidsai-csp-utils/issues/30
=> Update update_modules.py with try and except

colab/rapids-colab.sh
adding cuspatial patch for gdal and new verbiage around pegging to 0.14 or now
=> Peg Colab, fix cuspatial

colab/env-check.py
=> Update env-check.py to add V100 support

colab/rapids-colab.sh
fixes issue #36
updates language to show that the version of rapids is old and there are alternatives
thanks, community, for their exploration and finding some solution options
=> Updated rapids-colab.sh for issue #36

colab/rapids-colab.sh
Remove `defaults` channel from conda build
=> ENH Remove defaults channel from conda build

colab/rapidsai13.yml, colab/rapidsai14.yml
Remove conda defaults channel in environments
=> ENH Remove conda defaults channel in environments

colab/rapids-colab.sh
cupy install via conda doesn't stick.  it does with pip.  Solves SO issue: https://stackoverflow.com/questions/67368715/cuml-fit-functions-throwing-cp-full-typeerror
=> fix cupy install for colab

README.md, colab/install_rapids.py
release has happened.  finishes #47
=> update readme and versions to 21.06

colab/install_rapids.py
- Removed blazing option
- added new library
- updated versions
=> Update colab install to 21.08

colab/install_rapids.py
Update RAPIDS Colab script to 21.12 Stable
=> update versions in like with rapids 12.12 stable

colab/env-check.py, colab/install_rapids.py, colab/pip-install.py
test colab notebook https://colab.research.google.com/drive/1RU2D0OfUp9vkpPnZGN1pSUrVtf_HcvPz?usp=sharing
=> Add new pip installation to RAPIDS-Colab install script

colab/pip-install.py
via 
https://github.com/rapidsai/cuml/issues/5237
=> update index url for colab install

colab/pip-install.py
Sets version to 22.12 for python 3.9 compatibility.
Closes #70
=> Pin to 22.12 for Py3.9 compat

colab/pip-install.py
We need to make additional package pinnings to have a more predictably successful install.  Thanks @John Z
=> Add additional pinnings for 22.12 rapids version install

colab/pip-install.py
Using new pip packages for colab
Closes #70
=> [REVIEW] remove package pinning and update text

colab/env-check.py, colab/install_rapids.py, colab/update_gcc.sh
=> Pin conda install to 22.12, update to python 3.9

colab/pip-install.py
=> Update pip-install.py for cudf on colab

colab/pip-install.py
update pip template to include
=> Update for 24.06 and new installation options

colab/pip-install.py
=> Update pip-install for 24.08.py

colab/pip-install.py
Update RPAIDS install to 24.10
=> Update rapids install to 24.10

colab/pip-install.py
Update pip-install.py as colab updated to 24.10
=> colab updated to 24.10

colab/pip-install.py
updated latest, legacy, and nightly versions
=> 24.12 updates

colab/pip-install.py
uv fails pip install.  Regular pip works.
=> return nightlies install to standard pip

colab/pip-install.py
updating install script to work with the 25.02 release
=> 25.02 pip install update

colab/pip-install.py
=> update for colab installed version change to 25.02

colab/pip-install.py
update and test rapids versions
=> Update pip-install.py to 25.04
